
spring:
  data:
    mongodb:
      uri: mongodb+srv://SaimandsRoy:Saimandsroy2005@cluster0.j73tf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


      database: journaldb
      auto-index-creation: true


  redis:
    host: redis-18819.c305.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 18819
    password: zWfPRB2ZflKB4SMbr3D89PkDHFOZW3Dg
  mail:
    host: smtp.gmail.com
    port: 587
    username: kumarsaimand@gmail.com
    password: fpoy vsna imyh uzqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




server:
  port: 8080
  servlet:
    context-path: /journal



weather_api_key: af07c490cbe97c762a9860b60a515de7
  










